site_name: Algagyak

theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: teal

nav:
  - Home: index.md
  - Planets Cycles: planets_cycles.md
  - Grid Paths I. : grid_paths.md